update-app-doc: Fixing MD code block indenting
Each (new) line within a Markdown code block must be indented to prevent
parsing errors.

Apart from that, this commit also adds the missing exsl name space declaration
to fix the following error:

runtime error: file update-app-doc.xsl line 199 element choose
function-available() : prefix exsl is not bound

              ERROR: template implementation of str:replace relies on exsl:node-set().